from . import queries


class PreparedQuery:
    def __init__(self, session):
        self.select_district = session.prepare(queries.select_district)
        self.update_d_o_id_counter = session.prepare(queries.update_district_o_id_counter)
        self.update_stock_quantity = session.prepare(queries.update_stock_quantity)
        self.update_stock_ytd_and_order_cnt_counter = session.prepare(queries.update_stock_ytd_and_order_cnt)
        self.inc_stock_remote_cnt = session.prepare(queries.update_stock_remote_cnt_change)
        self.update_warehouse_ytd_change = session.prepare(queries.update_warehouse_ytd_change)
        self.update_district_ytd_change = session.prepare(queries.update_district_ytd_change)
        self.update_customer_payment_counters = session.prepare(queries.update_customer_payment_counters)
        self.update_order_carrier_id = session.prepare(queries.update_order_carrier_id)
        self.update_ol_deliver_d = session.prepare(queries.update_order_line_delivery_d)
        self.update_customer_delivery_change = session.prepare(queries.update_customer_delivery_counters)
        self.insert_ol = session.prepare(queries.insert_order_line)
        self.insert_order = session.prepare(queries.insert_order)
        self.insert_coi = session.prepare(queries.insert_customer_order_items)
        self.select_item = session.prepare(queries.select_item)
        self.select_stock = session.prepare(queries.select_stock)
        self.select_warehouse = session.prepare(queries.select_warehouse)
        self.select_customer = session.prepare(queries.select_customer)
        self.select_order_with_carrier = session.prepare(queries.select_order_with_carrier)
        self.select_ol = session.prepare(queries.select_order_line)
        self.select_order_with_customer = session.prepare(queries.select_order_with_customer)
        self.select_ol_in_range = session.prepare(queries.select_order_line_in_range)
        self.select_order_in_range = session.prepare(queries.select_order_in_range)
        self.select_customer_sort_by_balance = session.prepare(queries.select_customer_sort_by_balance)
        self.select_customer_order_items_in = session.prepare(queries.select_customer_order_items_in)
        self.select_customer_order_items = session.prepare(queries.select_customer_order_items)
        self.select_customer_by_district = session.prepare(queries.select_customer_by_district)
        self.insert_related_customer = session.prepare(queries.insert_related_customer)
        self.select_related_customer = session.prepare(queries.select_related_customer)
        self.select_district_o_id_change = session.prepare(queries.select_district_o_id_change)
